### ISSUE TITLE
Bump graceful-fs dependency

### ISSUE THREAD

**Issue by ChALkeR** [slang800/fobject#4]
`graceful-fs` versions lower than v4 reevaluate native `fs` module source, which is not supported.
You should update your `graceful-fs` dependency to v4 or later. 

Tracking issue: https://github.com/nodejs/node/issues/5213.

**Comment by eddiemonge** [comment]
@slang800 ^^

**Comment by lookfirst** [comment]
Please @slang800!

**Comment by slang800** [comment]
I'd gladly take a PR for this

**Comment by lookfirst** [comment]
I'm already on node 6 (brew installed), moving backwards is a pain and can't even `npm install` your project anymore (even after updating all the dependencies).

```
npm install
npm WARN deprecated wrench@1.3.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v6.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN prefer global marked@0.2.8 should be installed with -g

> jsdoc@3.3.0-alpha2 postinstall /Users/jon/checkout/fobject/node_modules/jsdoc
> node ./node/postinstall.js

Unable to create a symbolic link from /Users/jon/checkout/fobject/node_modules/jsdoc/lib/jsdoc to /Users/jon/checkout/fobject/node_modules/jsdoc/node_modules/jsdoc. Error: ENOENT: no such file or directory, symlink '/Users/jon/checkout/fobject/node_modules/jsdoc/lib/jsdoc' -> '/Users/jon/checkout/fobject/node_modules/jsdoc/node_modules/jsdoc'

fobject@0.0.3 /Users/jon/checkout/fobject
├── graceful-fs@4.1.3
├── UNMET PEER DEPENDENCY jsdoc@3.3.0-alpha2
├─┬ mocha@2.4.5
│ ├─┬ debug@2.2.0
│ │ └── ms@0.7.1
│ ├── diff@1.4.0
│ ├── mkdirp@0.5.1
│ └── supports-color@1.2.0
├── semver@5.1.0
└─┬ should@8.3.1
  ├── should-equal@0.7.2
  ├── should-format@0.3.2
  └── should-type@0.2.0

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/6.0.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! jsdoc@3.3.0-alpha2 postinstall: `node ./node/postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jsdoc@3.3.0-alpha2 postinstall script 'node ./node/postinstall.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the jsdoc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./node/postinstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs jsdoc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls jsdoc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jon/checkout/fobject/npm-debug.log
```

**Comment by lookfirst** [comment]
Similar issue with node 5.11.0

**Comment by notslang** [comment]
Ok, should be fixed by 34215027eda2679d59aae6f2564d987e21a0bf33! Comment if you run into further issues.

**Comment by lookfirst** [comment]
wait, what the f*ck? you changed the license to GPL3!?!?!?!?!?

**Comment by notslang** [comment]
Yeah, I've been gradually moving most of my packages over to the GPL... It helps ensure that development stays free and that code I write can't be used to take away a user's freedoms.

But by the tone of your comment, that sounds like a problem... care to elaborate?

**Comment by lookfirst** [comment]
https://www.youtube.com/watch?v=PaKIZ7gJlRU

**Comment by lookfirst** [comment]
MIT or BSD is the right solution here. Your idea of freedom is misplaced and misguided. Freedom isn't about forcing people to do something.

**Comment by notslang** [comment]
> https://www.youtube.com/watch?v=PaKIZ7gJlRU

I actually like the anti-tivoization clause... Being able to modify your software without running into DRM is a huge part of software freedom. I can see Linus' point about the overreach, and if you have a compelling use-case I'd be happy to add GPL-2.0 to whatever project you need, but in general I don't like DRM and I don't want to contribute to any system that uses DRM to restrict users.

> Freedom isn't about forcing people to do something.

I'm not forcing anyone to do anything - I'm refusing to let future versions of fobject be forked and turned into proprietary projects. If people don't have the basic decency to release their source code modifications, then they can write their own promise-based file objects.
